version: "3"

services:
  # Lets define our individual services
  flask:
    # Build the flask service using the Dockerfile in the flask directory
    build: ./flask

    # A friendly name for the flask container
    container_name: flask

    # Instruct Docker to always restart the service either in reboot or when the app crashes
    restart: always

    # Use environment to set any environment variables
    environment:
      - APP_NAME=bitwalla-Test

    # Any ports listed using `expose` will only be accessible to internal services/containers
    # uWSGI will be serving our Flask application on port 8080
    # This architecture is for protecting the app from direct access to the public
    expose:
      - 8080
    # Mount the container log directory to the local log directory
    # Consider changing this to /var/log/uwsgi:/var/log/uwsgi in production
    # Just make sure the directory exists before running docker-compose up --build
    volumes:
      - ./log/uwsgi:/var/log/uwsgi

  nginx:
    # Build the nginx service using the Dockerfile in the nginx directory
    build: ./nginx

    # Give our nginx container a friendly name
    container_name: nginx

    # Instruct Docker to always restart the service
    restart: always

    # Any ports listed using `ports` will be exposed to the outside world
    ports:
      - "80:80"

    # Mount the container log directory to the local log directory
    # Consider changing this to /var/log/nginx:/var/log/nginx in production
    # Just make sure the directory exists before running docker-compose up --build
    volumes:
      - ./log/nginx:/var/log/nginx
