version: "3"

services:
  # Define our individual services

  nginx:
    build: ./nginx
    container_name: nginx-app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/log/nginx:/var/log/nginx

  flask:
    build: ./flask
    container_name: flask-app
    restart: always
    environment:
      - APP_NAME=${APP_NAME}
      - VIRTUAL_HOST=${APP_DOMAIN}
    expose:
      - 8080
    volumes:
      - ./var/log/uwsgi:/var/log/uwsgi
